#!/bin/sh
#
# /etc/rc.d/racoon: start/stop racoon daemon
#

PIDFILE=/var/run/racoon.pid

case $1 in
start)
	/usr/sbin/racoon
	;;
stop)
	kill $(cat $PIDFILE)
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
